spring:
  cloud:
    azure:
      cosmos:
        endpoint: ${AZURE_COSMOS_URI}
        key: ${AZURE_COSMOS_KEY}
        database: ${AZURE_COSMOS_DATABASE}
        consistency-level: SESSION
    function:
      definition: ingestCosmosDb
    stream:
      bindings:
        ingestCosmosDb-in-0:
          destination: ${TOPIC_IN:general.alimentos.retail.guatemala.procesada}
          group: ${GROUP_IN:IngestaCosmos}
          consumer:
            concurrency: ${CONSUMER_CONCURRENCY:5}
      binders:
        local-solace:
          type: solace
          environment:
            solace:
              java:
                host: ${SOLACE_HOST}
                msgVpn: ${SOLACE_VPN}
                clientUsername: ${SOLACE_USERNAME}
                clientPassword: ${SOLACE_PASSWORD}
                connectRetries: ${SOLACE_CONNECT_RETRIES:3}
                connectRetriesPerHost: ${SOLACE_CONNECT_RETRIES_PER_HOST:0}
                reconnectRetries: ${SOLACE_RECONNECT_RETRIES:3}
      solace:
        bindings:
          ingestCosmosDb-in-0:
            consumer:
              queueAdditionalSubscriptions: ${TOPIC_SUB:general/alimentos/retail/guatemala/procesada}

server:
  port: ${SERVER_PORT:8093}
